// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Source               string       `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp            int64        `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Items                []*EventItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetItems() []*EventItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type EventItem struct {
	Transmitter          string   `protobuf:"bytes,1,opt,name=Transmitter,proto3" json:"Transmitter,omitempty"`
	Metric               string   `protobuf:"bytes,2,opt,name=Metric,proto3" json:"Metric,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventItem) Reset()         { *m = EventItem{} }
func (m *EventItem) String() string { return proto.CompactTextString(m) }
func (*EventItem) ProtoMessage()    {}
func (*EventItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *EventItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventItem.Unmarshal(m, b)
}
func (m *EventItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventItem.Marshal(b, m, deterministic)
}
func (m *EventItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventItem.Merge(m, src)
}
func (m *EventItem) XXX_Size() int {
	return xxx_messageInfo_EventItem.Size(m)
}
func (m *EventItem) XXX_DiscardUnknown() {
	xxx_messageInfo_EventItem.DiscardUnknown(m)
}

var xxx_messageInfo_EventItem proto.InternalMessageInfo

func (m *EventItem) GetTransmitter() string {
	if m != nil {
		return m.Transmitter
	}
	return ""
}

func (m *EventItem) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *EventItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "models.Event")
	proto.RegisterType((*EventItem)(nil), "models.EventItem")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x85, 0xa9, 0xa1, 0x85, 0x5c, 0x27, 0x83, 0x48, 0x06, 0x87, 0xd0, 0xc5, 0x4e, 0x1d, 0xf4,
	0x37, 0x38, 0x38, 0xb8, 0x04, 0x71, 0x71, 0xaa, 0xf5, 0x84, 0x40, 0xd3, 0x94, 0xe4, 0xea, 0xef,
	0x97, 0xa6, 0x41, 0x1d, 0xbf, 0xef, 0xe0, 0xbd, 0x7b, 0x50, 0xe2, 0x1b, 0x07, 0x6a, 0x46, 0xef,
	0xc8, 0x89, 0xc2, 0xba, 0x27, 0xf6, 0xa1, 0x7a, 0x41, 0x7e, 0x9a, 0xb5, 0xd8, 0x42, 0x11, 0xdc,
	0xe4, 0x3b, 0x94, 0x99, 0xca, 0x6a, 0xae, 0x13, 0x89, 0x1d, 0x70, 0x32, 0x16, 0x03, 0xb5, 0x76,
	0x94, 0x2b, 0x95, 0xd5, 0x4c, 0xff, 0x84, 0xd8, 0x43, 0x6e, 0x08, 0x6d, 0x90, 0x4c, 0xb1, 0xba,
	0x3c, 0xac, 0x9b, 0x25, 0xb6, 0x89, 0x99, 0x67, 0x42, 0xab, 0x97, 0x7b, 0x75, 0x07, 0xfe, 0x75,
	0x42, 0x41, 0x79, 0xf5, 0xed, 0x10, 0xac, 0x21, 0x42, 0x9f, 0x0a, 0xff, 0xd5, 0xfc, 0xcd, 0x05,
	0xc9, 0x9b, 0x2e, 0x56, 0x72, 0x9d, 0x48, 0x6c, 0x20, 0xbf, 0xb5, 0xfd, 0x84, 0x92, 0x45, 0xbd,
	0xc0, 0xa3, 0x88, 0x9b, 0x8e, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x88, 0x90, 0x22, 0xe2,
	0x00, 0x00, 0x00,
}
