// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Source               string               `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Items                map[string]*Item     `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Event) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Event) GetItems() map[string]*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Item) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "models.Event")
	proto.RegisterMapType((map[string]*Item)(nil), "models.Event.ItemsEntry")
	proto.RegisterType((*Item)(nil), "models.Item")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573) }

var fileDescriptor_0b5431a010549573 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xcd, 0x6a, 0xc3, 0x30,
	0x10, 0x84, 0x51, 0xfc, 0x03, 0x5e, 0xe7, 0x50, 0x96, 0x52, 0x8c, 0x2f, 0x35, 0x3e, 0xf9, 0xb4,
	0x29, 0xee, 0xa5, 0xf4, 0x9e, 0x42, 0xaf, 0xa2, 0x2f, 0x90, 0xb4, 0xdb, 0x10, 0x6a, 0x45, 0xc6,
	0x92, 0x03, 0x7e, 0xc2, 0xbe, 0x56, 0xd1, 0x8f, 0x69, 0x6e, 0xda, 0x99, 0xf9, 0x66, 0x57, 0xb0,
	0x55, 0xfa, 0x8b, 0x07, 0x43, 0xe3, 0xa4, 0xad, 0xc6, 0x3c, 0x4c, 0xf5, 0xe3, 0x49, 0xeb, 0xd3,
	0xc0, 0x3b, 0xaf, 0x1e, 0xe7, 0xef, 0x9d, 0x3d, 0x2b, 0x36, 0xf6, 0xa0, 0xc6, 0x10, 0x6c, 0x7f,
	0x05, 0x64, 0xfb, 0x2b, 0x5f, 0x2c, 0x12, 0xa4, 0xce, 0xac, 0x44, 0x23, 0xba, 0xb2, 0xaf, 0x29,
	0x90, 0xb4, 0x92, 0xf4, 0xb1, 0x92, 0xd2, 0xe7, 0xf0, 0x01, 0x72, 0xa3, 0xe7, 0xe9, 0x93, 0xab,
	0x4d, 0x23, 0xba, 0x42, 0xc6, 0x09, 0x09, 0xb2, 0xb3, 0x65, 0x65, 0xaa, 0xa4, 0x49, 0xba, 0xb2,
	0xaf, 0x28, 0x1e, 0xe6, 0xb7, 0xd0, 0xbb, 0xb3, 0xf6, 0x17, 0x3b, 0x2d, 0x32, 0xc4, 0xea, 0x37,
	0x80, 0x7f, 0x11, 0xef, 0x20, 0xf9, 0xe1, 0xc5, 0x1f, 0x51, 0x48, 0xf7, 0xc4, 0x16, 0xb2, 0xeb,
	0x61, 0x98, 0xc3, 0x9a, 0xb2, 0xdf, 0xae, 0x7d, 0x0e, 0x92, 0xc1, 0x7a, 0xdd, 0xbc, 0x88, 0xf6,
	0x09, 0x52, 0x27, 0x21, 0x42, 0x6a, 0x97, 0x91, 0x63, 0x85, 0x7f, 0xe3, 0xfd, 0x6d, 0x47, 0x11,
	0xa9, 0x63, 0xee, 0xff, 0xf6, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x61, 0xe8, 0x77, 0xc9, 0x3b,
	0x01, 0x00, 0x00,
}
